### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by Alhadis** [Alhadis/Nag#1]
## To-do list
- [X] Rename `kickOn` to ~~`kickBy`~~ `kickWhen` (Done in e075c234)
- [X] Use a less ambiguous name for the parameter that sets nag-triggering event type (Done in c84017e)
- [X] Wrap initialisation code in an internal function (Done in 1eb8fc83)
- [X] Extend `.reset` method with an optional parameter to reinitialise `Nag` instance (Done in 1eb8fc83)
- [X] Find a less ugly way to document options in `README.md` (Done in 1cf3c105)
- [x] Document instance methods in `README.md` and remove spaces from options list (Done in 1ea70e6)
- [x] Call `.kickWhen` method from constructor if a `kickWhen` object was passed to options hash (Done in b95ede7, along with a crapload of well-deserved refactoring)
- [X] Clean `README.md` up and make it BitBucket-friendly by removing the `<br/>` tags (Done in 53b68b5)
